server:
  port: 8383

spring:
  application-name: coffee
  # Oracle DB
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.30.1.54:1521/xe
    username: s202507a
    password: 704A

  # View Resolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  security:
    user:
      name: test
      password: test

mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml

com.oracle.coffee.upload.path: upload