server:
  port: 8383

spring:
  application-name: coffee
  # Oracle DB
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@172.30.1.26:1521/xe
#    username: S202507A
#    password: 704A
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: person01
    password: tiger
    
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.OracleDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update

  # View Resolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  security:
    user:
      name: test
      password: test

mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml