server:
  port: 8383

spring:
  application-name: coffee
  # Oracle DB     localhost --> 공용 db Ipv4
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.30.1.64:1521/xe
    username: S202507A
    password: 704A

  # View Resolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  security:
    user:
      name: test
      password: test

mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml