server:
  port: 8384
#Oracle Connect
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: scottJpa
    password: tiger

# View Resolver  --> tymleaf

# JPA Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update